name: retrofit_bloc_go_router_getit
description: "Shown Usage of retrofit,flutter_bloc,get_it and go_router"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  json_serializable: ^6.8.0



flutter:

  uses-material-design: true

  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png

